version: '3.8'

services:
  db:
    image: mysql:5.7
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: vkvkdl23  # Set the root password here
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: root                    # Regular user
      MYSQL_PASSWORD: vkvkdl23       # Password for the regular user
    ports:
      - "3306:3306"

  web:
    build: .
    container_name: django_web
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=mydatabase
      - DB_USER=user
      - DB_PASSWORD=user_password
