version: '3'

services:
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: qwe123
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: tophia
      MYSQL_PASSWORD: vkvkdl23
    ports:
      - "3306:3306"  # Correct the port mapping if necessary

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - MYSQL_DATABASE=mydatabase
      - MYSQL_USER=tophia
      - MYSQL_PASSWORD=vkvkdl23
      - MYSQL_HOST=db
      - MYSQL_PORT=3306

volumes:
  db_data:
