# Generated by Django 5.0.6 on 2024-07-15 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
    ]
